language: php

php:
  - 7.2
  - 7.3
  - 7.4

node_js:
  - 10

services:
  - xvfb

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

before_script:
   - travis_retry composer self-update
   - travis_retry composer clear-cache
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest
   - chmod -R o+w vendor/orchestra
   - vendor/orchestra/testbench-dusk/create-sqlite-db
   - vendor/bin/dusk-updater update
   - vendor/bin/dusk-updater detect --auto-update
   - vendor/laravel/dusk/bin/chromedriver-linux &
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - vendor/bin/phpunit --testsuite=Browser
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - rm -R public/css
  - rm -R public/js
  - npm cache clear --force
  - npm install
  - npm run production

deploy:
  target_branch: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  on:
    branch: master
    condition: $(phpenv version-name) = "7.3"

notifications:
  email:
    recipients:
      - bliz48rus@gmail.com
      - salador2005@yandex.ru
    on_success: never
    on_failure: always
