language: php

php:
  - 7.0
  - 7.1

sudo: required
dist: trusty

addons:
   chrome: stable
   postgresql: "9.4"

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql

before_install:
  - psql -c 'create database platform;' -U postgres
  - psql -c "CREATE USER orchid WITH PASSWORD 'orchid';" -U postgres  
  
install:
  - composer install --prefer-source

before_script:
   - chmod -R o+w vendor/orchestra
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script: vendor/bin/phpunit

notifications:
  email: false
