name: Dusk tests

on: [push,pull_request]

jobs:
  dusk-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: PHP version
        run: php -v

      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Make SQLite database
        run: vendor/orchestra/testbench-dusk/create-sqlite-db

      - name: Update Dusk Chromedriver
        run: vendor/bin/dusk-updater detect --auto-update

      - name: Execute Unit Tests
        run: vendor/bin/phpunit

      - name: Upload Failed Screenshots
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots/*
